# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nbayes 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "nbayes".freeze
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["oasic".freeze]
  s.date = "2020-06-26"
  s.description = "Ruby implementation of Naive Bayes that generates true probabilities per class, works with many token types, and provides lots of bells and whistles while being optimized for performance.".freeze
  s.email = "j@oasic.net".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/nbayes.rb",
    "nbayes.gemspec",
    "spec/nbayes_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/oasic/nbayes".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.14".freeze
  s.summary = "Full-featured Ruby implementation of Naive Bayes classifier".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>.freeze, [">= 3.9.0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 3.0.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 2.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 2.3.0"])
    else
      s.add_dependency(%q<rspec>.freeze, [">= 3.9.0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 3.0.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 2.0.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<rspec>.freeze, [">= 3.9.0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 3.0.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 2.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 2.3.0"])
  end
end

